In [1]:
def my_function():
    "This prints a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [3]:
def printme(nama):
    "this prints a nama string into this function"
    print(nama)

In [4]:
printme("widi")

widi


In [5]:
printme("nama saya adalah....")

nama saya adalah....


In [6]:
def printme(nama, alamat):
    "this prints a nama string into this function"
    print(nama)
    print(alamat)

In [7]:
printme("widi", "medan")

widi
medan


In [8]:
printme(alamat="medan", nama="widi")

widi
medan


In [50]:
def printme(nama = "widi", alamat = "medan"):
    "this prints a inama string into this function"
    print(nama)
    print(alamat)
    return;

In [29]:
def printinfo(arg1, *vartuple):
    "this prints a variable passed arguments"
    print("output is: ")
    print(arg1)
    for var in vartuple:
        print(var)
        return;

In [20]:
printinfo(30)

output is: 
30


In [30]:
printinfo(1, 2, 3, 4, 5, 6, 7, 8, 9)

output is: 
1
2


In [25]:
sum = lambda arg1, arg2: arg1 + arg2;

In [26]:
sum(10, 20)

30

In [28]:
print("value of total:", sum(20, 20))

value of total: 40


In [35]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [36]:
sum(10, 20)

(30, 80)

In [47]:
kucing = 20

def jumlahHewan():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahHewan():
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [48]:
jumlahHewan()

50

In [49]:
tambahHewan()

40

In [51]:
import sys

In [52]:
sys.path

['C:\\Users\\Lenovo',
 'C:\\Users\\Lenovo\\anaconda3\\python37.zip',
 'C:\\Users\\Lenovo\\anaconda3\\DLLs',
 'C:\\Users\\Lenovo\\anaconda3\\lib',
 'C:\\Users\\Lenovo\\anaconda3',
 '',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Lenovo\\.ipython']

In [55]:
sys.path.append(r'\Users\Lenovo\desktop\H8package')

In [58]:
sys.path

['C:\\Users\\Lenovo',
 'C:\\Users\\Lenovo\\anaconda3\\python37.zip',
 'C:\\Users\\Lenovo\\anaconda3\\DLLs',
 'C:\\Users\\Lenovo\\anaconda3\\lib',
 'C:\\Users\\Lenovo\\anaconda3',
 '',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Lenovo\\.ipython',
 'C:\\Users\\Lenovo\\desktop\\H8package',
 '\\Users\\Lenovo\\desktop\\H8package']

In [59]:
sys.path.append(r'\Users\Lenovo\desktop\H8package')

In [60]:
sys.path

['C:\\Users\\Lenovo',
 'C:\\Users\\Lenovo\\anaconda3\\python37.zip',
 'C:\\Users\\Lenovo\\anaconda3\\DLLs',
 'C:\\Users\\Lenovo\\anaconda3\\lib',
 'C:\\Users\\Lenovo\\anaconda3',
 '',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Lenovo\\.ipython',
 'C:\\Users\\Lenovo\\desktop\\H8package',
 '\\Users\\Lenovo\\desktop\\H8package',
 '\\Users\\Lenovo\\desktop\\H8package']

In [61]:
import mod

In [62]:
mod.s

'Hacktive Inalum for Data Science'

In [63]:
mod.a

[100, 200, 300]

In [64]:
mod.foo('widi')

widi


In [65]:
from mod import s, foo

In [66]:
s

'Hacktive Inalum for Data Science'

In [67]:
foo('widi')

widi


In [68]:
from mod import *

In [69]:
s

'Hacktive Inalum for Data Science'

In [72]:
from mod import s as string

In [73]:
string

'Hacktive Inalum for Data Science'

In [74]:
import mod as my_module

In [76]:
my_module.a

[100, 200, 300]

In [78]:
my_module.s

'Hacktive Inalum for Data Science'

In [79]:
import numpy as np

In [80]:
import H8package.mod

H8package.mod.s

ModuleNotFoundError: No module named 'H8package'

In [82]:
sys.path.append(r'/Users/Lenovo/desktop/')

In [83]:
import H8package.mod

H8package.mod.s

'Hacktive Inalum for Data Science'

In [84]:
!pip --version

pip 20.0.2 from C:\Users\Lenovo\anaconda3\lib\site-packages\pip (python 3.7)



In [85]:
!pip install requests

In [86]:
import requests

In [87]:
!pip install statistics

  Created wheel for statistics: filename=statistics-1.0.3.5-py3-none-any.whl size=7458 sha256=59544c4e6b48200c2851e91a5024914307d9475176561870b391ca5f18dc7c36
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\37\09\e1\49ee45c0ce248a6e9c986aae82d32bbcba09c9f3b9d0c3406a
Successfully built statistics


In [88]:
import statistics

In [89]:
## numpy

In [90]:
import numpy as np

In [91]:
## creating array

a = np.array([1, 2, 3])

In [92]:
a

array([1, 2, 3])

In [93]:
b = [1, 2, 3]

In [94]:
b

[1, 2, 3]

In [96]:
c = np.zeros(5)

In [97]:
print(c)

[0. 0. 0. 0. 0.]


In [99]:
d = np.ones(5)

In [100]:
print(d)

[1. 1. 1. 1. 1.]


In [101]:
np.arange(4)

array([0, 1, 2, 3])

In [102]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.arange(0, 20, 2) #start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [106]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
print(arr)

[1 2 3 4 5 6 7 8]


In [108]:
np.append(arr, [1, 2]) #add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [109]:
np.delete(arr, 1) #delete

array([1, 3, 4, 5, 6, 7, 8])

In [110]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [111]:
print(arr)

[2 1 5 3 7 4 6 8]


In [112]:
np.sort(arr) #sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
## shape dan size

In [119]:
# Reshape

In [121]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [122]:
b = a.reshape(3,2)

In [123]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [124]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
#convert 1D to 2D

In [126]:
a

array([0, 1, 2, 3, 4, 5])

In [127]:
a.shape

(6,)

In [129]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [131]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)


[[0 1 2 3 4 5]]
(1, 6)


In [132]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [133]:
print(a.shape)

(6,)


In [134]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [135]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [136]:
## indexing and slicing

In [137]:
data = np.array([1, 2, 3])

In [138]:
data[0]

1

In [139]:
data[1]

2

In [140]:
data[0:2]

array([1, 2])

In [141]:
data[1:]

array([2, 3])

In [142]:
data[-2]

2

In [143]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [144]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [146]:
a[a<5]

array([1, 2, 3, 4])

In [147]:
lebih_lima = (a>=5)

a[lebih_lima]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
a[(a>2)&(a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
# create array form existing data

In [150]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [153]:
arr1 = arr[3:9]

In [154]:
print(arr1)

[4 5 6 7 8 9]


In [157]:
a_1 = np.array([[1, 1],
              [2, 2]])
print(a_1)

[[1 1]
 [2 2]]


In [159]:
a_2 = np.array([[3, 3],
              [4, 4]])
print(a_2)

[[3 3]
 [4 4]]


In [160]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [161]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [162]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [164]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [165]:
# view dan copy

In [166]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [167]:
b = a.view()

In [168]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [169]:
c = a.copy()

In [170]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [171]:
# basic array operations

In [172]:
a_1

array([[1, 1],
       [2, 2]])

In [173]:
a_2

array([[3, 3],
       [4, 4]])

In [176]:
a_2 - a_1

array([[2, 2],
       [2, 2]])

In [177]:
a_2 + a_1

array([[4, 4],
       [6, 6]])

In [178]:
a_2 * a_1

array([[3, 3],
       [8, 8]])

In [179]:
a_2 / a_1

array([[3., 3.],
       [2., 2.]])

In [180]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [181]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
arr.sum()

55

In [183]:
a_1

array([[1, 1],
       [2, 2]])

In [185]:
a_1.sum()

6

In [186]:
a_1.sum(axis=0)

array([3, 3])

In [187]:
a_1.sum(axis=1)

array([2, 4])

In [189]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [190]:
a.sum()

78

In [191]:
a.min()

1

In [192]:
a.max()

12

In [193]:
a.min(0)

array([1, 2, 3, 4])

In [194]:
a.min(1)

array([1, 5, 9])

In [195]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [196]:
a.max(axis=1)

array([ 4,  8, 12])

In [197]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [198]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [199]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [200]:
np.random.random((3,2))

array([[0.14383105, 0.53776709],
       [0.28923793, 0.66492164],
       [0.83898119, 0.47678894]])

In [201]:
# matrix arithetic

In [204]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [208]:
ones = np.array([[1,1],[1,1]])
print(ones)

[[1 1]
 [1 1]]


In [209]:
print(data+ones)

[[2 3]
 [4 5]]


In [210]:
ones_row=np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [212]:
data+ones_row

array([[2., 3.],
       [4., 5.]])

In [213]:
a_1=np.array([[1,2,3],[4,5,6]])
print(a_1)

a_2=np.array([[7,8],[9,10],[11,12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [214]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [215]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [216]:
data = np.array([[1,2],[3,4], [5,6]])

In [217]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [219]:
data[0,1]

2

In [220]:
data[1,1]

4

In [222]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [223]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [224]:
data[0:2,0]

array([1, 3])

In [225]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [226]:
data.max()

6

In [227]:
data.min()

1

In [228]:
data.sum()

21

In [229]:
data.max(axis=0)

array([5, 6])

In [230]:
# Transosing and reshaping

In [231]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [232]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [234]:
data_col=np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [235]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [236]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [238]:
arr = np.arange(6).reshape((2,3))

In [239]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [240]:
# ND Array

In [242]:
ndarr = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])

In [244]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [245]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [246]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [247]:
np.random.random((4,3,2))

array([[[0.08617537, 0.26045944],
        [0.7376281 , 0.77929476],
        [0.11453368, 0.49290547]],

       [[0.32457591, 0.00982467],
        [0.74951389, 0.42121705],
        [0.62818803, 0.6165943 ]],

       [[0.37077754, 0.56298092],
        [0.64516931, 0.51512093],
        [0.3593954 , 0.62615321]],

       [[0.51030944, 0.57416589],
        [0.37938812, 0.63636654],
        [0.72237408, 0.85494802]]])

In [248]:
# flatten

In [250]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [251]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [252]:
a = np.random.random(5)

In [253]:
print(a)

[0.46733168 0.2298207  0.12597797 0.59794695 0.15267892]


In [254]:
a.shape #rank 1 Array

(5,)

In [255]:
a.T

array([0.46733168, 0.2298207 , 0.12597797, 0.59794695, 0.15267892])

In [256]:
np.dot(a, a.T)

0.6679383090322855

In [257]:
a=np.random.rand(5,1) #column vector

In [258]:
print(a)

[[0.65206762]
 [0.06687203]
 [0.6834166 ]
 [0.71225014]
 [0.1207954 ]]


In [259]:
a.shape

(5, 1)

In [260]:
a.T

array([[0.65206762, 0.06687203, 0.6834166 , 0.71225014, 0.1207954 ]])

In [261]:
np.dot(a, a.T)

array([[0.42519218, 0.04360508, 0.44563383, 0.46443525, 0.07876677],
       [0.04360508, 0.00447187, 0.04570145, 0.04762961, 0.00807783],
       [0.44563383, 0.04570145, 0.46705825, 0.48676357, 0.08255358],
       [0.46443525, 0.04762961, 0.48676357, 0.50730026, 0.08603654],
       [0.07876677, 0.00807783, 0.08255358, 0.08603654, 0.01459153]])

In [262]:
a=np.random.rand(1,5)

In [263]:
a.shape

(1, 5)

In [264]:
ndarr = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])

In [265]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])